import = ["~/dotfiles/config/alacritty-theme/themes/nightfox.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13

[window]
option_as_alt = "OnlyLeft"
dynamic_padding = true

[shell]
program = "/opt/homebrew/bin/zellij"
args = ["-l", "welcome"]
