import = ["~/dotfiles/config/alacritty-theme/themes/dawnfox.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[window]
option_as_alt = "OnlyLeft"

[shell]
program = "/opt/homebrew/bin/zellij"
args = ["-l", "welcome"]
