vim.pack.add {
  { src = 'https://github.com/neovim/nvim-lspconfig' },
  { src = 'https://github.com/nvim-treesitter/nvim-treesitter' },
  { src = 'https://github.com/nvim-treesitter/nvim-treesitter-textobjects' },
  { src = 'https://github.com/shrey99sh/ts-node-select' },
  { src = 'https://github.com/windwp/nvim-ts-autotag' },
  { src = 'https://github.com/echasnovski/mini.nvim' },
  { src = 'https://github.com/folke/snacks.nvim' },
  { src = 'https://github.com/soerenbf/pi-nvim' },
  { src = 'https://github.com/folke/flash.nvim' },
  { src = 'https://github.com/jake-stewart/multicursor.nvim', version = '1.0' },
  { src = 'https://github.com/windwp/nvim-autopairs' },
  { src = 'https://github.com/danymat/neogen' },
  { src = 'https://github.com/mbbill/undotree' },
  { src = 'https://github.com/NeogitOrg/neogit' },
  { src = 'https://github.com/esmuellert/codediff.nvim' },
  { src = 'https://github.com/nvim-lua/plenary.nvim' },
  { src = 'https://github.com/MunifTanjim/nui.nvim' },
  { src = 'https://github.com/EdenEast/nightfox.nvim' },
  { src = 'https://github.com/nvim-lualine/lualine.nvim' },
  { src = 'https://github.com/folke/noice.nvim' },
  { src = 'https://github.com/utilyre/barbecue.nvim' },
  { src = 'https://github.com/SmiteshP/nvim-navic' },
  { src = 'https://github.com/nvim-tree/nvim-web-devicons' },
  { src = 'https://github.com/folke/which-key.nvim' },
  { src = 'https://github.com/folke/todo-comments.nvim' },
  { src = 'https://github.com/stevearc/conform.nvim' },
  { src = 'https://github.com/mfussenegger/nvim-lint' },
  { src = 'https://github.com/mrcjkb/rustaceanvim' },
  { src = 'https://github.com/folke/lazydev.nvim' },
  { src = 'https://github.com/Bilal2453/luvit-meta' },
  { src = 'https://github.com/MeanderingProgrammer/markdown.nvim' },
  { src = 'https://github.com/lervag/vimtex' },
  { src = 'https://github.com/stevearc/quicker.nvim'}
}
